### ISSUE TITLE
Display 'User has already been registered' message after successful submission

### ISSUE THREAD

**Issue by twocitizenships** [strikewalker/reacher#11]
After the user has been submitted and created successfully, display a message 'User already registered' or something of the sort.

https://user-images.githubusercontent.com/85661537/167749791-724358cf-a17a-455c-bcc8-83d9024988de.mp4

**Comment by strikewalker** [comment]
@twocitizenships, It is actually functioning as intended, just not very intuitive. There is already an update I need to push that allows you to "update your profile" and makes the experience more intuitive.
