### ISSUE TITLE
create an account page separate from /setup 

### ISSUE THREAD

**Issue by jacobpfickes** [strikewalker/reacher#8]
I think it would make sense to separate existing accounts out from the setup page. I think it would create a better UX and would open up the door for future features specific to existing users.

**Comment by strikewalker** [comment]
I agree. There also needs to be a way to edit the values, so we will want to reuse it too.

**Comment by jacobpfickes** [comment]
Yeah agreed. I can start trying to work through this.

**Comment by strikewalker** [comment]
I'm in the middle of some changes around this that I'd like to get merged today or tomorrow.

**Comment by jacobpfickes** [comment]
Ok great I'll keep any eye out

**Comment by strikewalker** [comment]
It's in. LMK if you have any questions.

**Comment by jacobpfickes** [comment]
Great! I'll start taking a look. How do the changes get pushed to the actual site? Do you just upload it manually? Just wondering

**Comment by strikewalker** [comment]
Awesome. Yes, it's a manual process right now.

**Comment by strikewalker** [comment]
@jacobpfickes, please check out the latest code and let me know if you have any questions.

**Comment by jacobpfickes** [comment]
@strikewalker Hey, I've applied to get access to the strike API so I can test better locally but haven't heard anything back yet. Any thoughts on what would be the best way to test locally without having an API key to plug in?

**Comment by strikewalker** [comment]
You should be able to get an API key pretty soon, but I'll reach out through Twitter to get you some test credentials.

**Comment by jacobpfickes** [comment]
Hey Sam, sorry for such a late response. The account page looks great. I'm going to go ahead and close this issue now.
